# Script to properly extract and add descriptions to BUILD.md files

$rootPath = "c:\Users\jeremyho\repos\industry-apps"

# Module descriptions extracted from backups
$descriptions = @{
    "programs-and-services" = "The **Programs and Services** module provides a structured framework for defining what an organization offers, who is eligible, who is participating, and what officially occurred as a result of service delivery. It separates strategic structure (Program, Service, Service Offering), eligibility configuration (Service Eligibility Rule and related scoping), and operational execution (Service Participation, Service Activity, Service Result), allowing services to be consistently defined and delivered across contexts. This module supports public sector use cases such as benefits administration, grants management, community assistance programs, and workforce initiatives, as well as commercial scenarios such as customer onboarding, subscription services, vendor programs, and training offerings. By cleanly distinguishing between enrollment, operational activities, and auditable outcomes, the module enables reusable service design, lifecycle tracking, and integration with related domains like Claims Processing, Permits and Licensing, Case Management, and Financial Management."
    
    "personnel-security" = "The **Personnel Security** module manages the lifecycle of evaluating, granting, monitoring, and enforcing trust-based access for individuals within an organization. It supports formal security reviews, background investigations, adjudication decisions, and the issuance of approved security eligibility levels. The module also enables ongoing oversight through continuous evaluation enrollment and the tracking of reportable events that may impact a person's access status. Operationally, it manages the issuance and status of access credentials tied to approved eligibility. Typical use cases include initial security vetting, clearance or trust renewals, eligibility upgrades, incident-triggered reviews, foreign travel or contact reporting, continuous monitoring programs, and badge or access credential management across government, defense, critical infrastructure, financial services, healthcare, and other regulated environments."
    
    "shift-scheduling" = "The **Shift Scheduling module** provides tables for managing workforce scheduling across operational contexts. It supports creating schedules for locations, defining shifts and staffing requirements, assigning individuals and teams to shifts, tracking participant availability, and managing recurring shift patterns. This module is designed for use cases such as retail operations, healthcare facilities, field operations, security posts, and other environments requiring structured shift-based coverage."
    
    "executive-coordination" = "The **Executive Coordination** module is used to formally track, govern, and oversee leadership-directed actions from issuance through completion. It captures the authority and intent behind an **Executive Action**, documents its legal or policy basis, assesses impacts and risks, and provides executive-level status visibility while operational work is managed through linked Action Items. This module is ideal for scenarios such as tracking responses to legislative or board inquiries, coordinating cross-department strategic initiatives, managing compliance-driven mandates, overseeing corrective actions from audits, directing inter-agency or interdepartmental efforts under formal agreements, or monitoring high-visibility operational taskers issued by executive leadership. It provides structured accountability and roll-up reporting without duplicating operational task tracking."
    
    "project-tracking" = "The **Project Tracking** module supports the structured intake, planning, execution, and control of work across initiatives of any size. It enables organizations to capture proposed work through Project Requests, formally manage approved Projects, plan delivery using Backlogs and Iterations, and execute work through categorized Work Items aligned to defined Roles and Resource Assignments. Milestones provide timeline checkpoints, while Change Requests ensure formal governance over scope, schedule, and cost adjustments. This module can be used for IT system implementations, policy initiatives, construction efforts, product development, operational improvements, research programs, or any structured body of work requiring visibility, accountability, and controlled delivery from initiation through completion."
    
    "member-organizations" = "The **Member Organizations** module manages structured groups of people formed for a defined purpose, such as boards, councils, committees, panels, clubs, associations, and teams. It supports defining the organization itself, classifying its type, managing members and their roles, handling membership applications and fees, and organizing service terms. For governance-focused groups, it also enables formal decision-making through motions, votes, vote responses, and resolutions, providing a clear record of proposals and adopted outcomes. This module can be used for scenarios such as a board of directors approving resolutions, a city council recording votes, a professional association managing dues-paying members, a university committee tracking terms and roles, or a club reviewing membership applications and documenting decisions."
    
    "external-interaction" = "The **External Interaction module** provides structured tracking for external communications and engagements with constituents, stakeholders, and the public. It supports intake, categorization, assignment, and response tracking for inquiries, requests, complaints, feedback, and other interaction types from individuals and organizations outside the entity."
    
    "financial-management" = "Financial Management is an end-to-end module that supports the planning, acquisition, contractual oversight, and financial execution of goods and services. It enables organizations to define budgets and funding sources, validate availability of funds, manage procurement processes, formalize agreements through contracts and amendments, issue purchase orders, record financial commitments, and process payments. The module supports use cases such as departmental budget control, competitive sourcing and vendor selection, contract lifecycle management, project- or grant-funded spending, compliance-driven funds certification, and structured payment tracking. It provides traceability from initial request through contract award to final payment, ensuring financial accountability, operational transparency, and audit readiness across both public sector and commercial environments."
    
    "training-and-certification" = "The **Training and Certification** module provides a comprehensive framework for managing learning delivery, academic programs, credentialing, and eligibility requirements across higher education, workforce development, and regulated industries. It supports defining training courses and sessions (classes), organizing structured curricula through learning paths and academic programs, tracking enrollments, attendance, and completions, and awarding certificates with lifecycle management including renewals and expiration tracking. The module also enables configurable qualification requirements that can be applied to roles, access privileges, programs, or operational activities, ensuring individuals meet required training, credential, or competency standards. Common use cases include university course and degree management, corporate learning and development, professional certification programs, compliance-driven training environments, apprenticeship models, and readiness or eligibility enforcement across enterprise operations."
    
    "time-travel-expenses" = "The **Time, Travel, and Expense** module provides a unified structure for capturing time worked, planning personnel availability, authorizing travel, and submitting reimbursable expenses within an organization. It enables individuals to record time against standardized **Time Codes**, plan future availability through **Time Commitments**, request and manage travel through **Travel Requests** and **Travel Segments**, and submit costs through **Expense Reports** and **Expense Items** categorized by defined **Expense Categories**. This module supports use cases such as operational time tracking (e.g., investigations, casework, internal initiatives), workforce planning and duty scheduling, travel authorization and itinerary management, reimbursement processing, and financial reporting alignment with organizational units or funding sources. It is designed to be reusable across public sector, nonprofit, and commercial environments, supporting both lightweight tracking needs and scalable financial governance."
    
    "operational-excellence" = "The **Operational Excellence** module provides a structured framework for managing incidents, inspections, exercises, readiness assessments, findings, recommendations, and personnel-reported operational impacts within a single governance model. It supports reactive scenarios such as investigating service disruptions or operational failures, as well as proactive activities like conducting inspections, running training exercises, and evaluating mission or go-live readiness. The module centralizes identified findings and recommended actions to ensure issues are tracked to resolution, while also capturing bottom-up operational impact submissions to highlight improvements and efficiencies. It is designed for cross-industry use cases including public sector oversight and emergency preparedness, healthcare and manufacturing quality management, corporate operational governance, program readiness validation, and continuous improvement initiatives."
    
    "investigations" = "The **Investigations module** supports the structured intake, management, analysis, and resolution of formal investigations across public sector and commercial environments. It enables organizations to document allegations, assign investigators, manage interviews and evidence with defensible chain-of-custody tracking, analyze issues against policies or standards, produce formal reports, and monitor corrective actions and recoveries through closure. The module supports use cases such as employee misconduct investigations, fraud inquiries, ethics hotline complaints, safety incidents, regulatory violations, data breach reviews, quality control investigations, inspector general cases, internal affairs reviews, and compliance examinations. It provides both operational case management and governance oversight, ensuring investigations are thorough, auditable, and aligned with organizational or statutory requirements."
    
    "it-service-management" = "The **IT Service Management (Lite) / IT System Catalog** module provides a structured framework for managing IT service offerings, access control, system inventory, technology standards, and compliance oversight in a unified model. It supports core operational use cases such as submitting and fulfilling service requests, processing access requests and entitlement assignments, publishing orderable IT catalog items, and tracking hosting environments. At the same time, it enables governance scenarios including documenting system components and technology stacks, managing compliance assessments and system accreditations, and tracking remediation activities through POAM items. The module is designed to balance day-to-day service delivery with architectural visibility and security oversight, making it suitable for both public sector and commercial organizations that need lightweight ITSM capabilities combined with structured system and technology governance."
    
    "hr-recruiting" = "The **HR Recruiting module** manages the end-to-end hiring lifecycle from workforce request through candidate selection and offer. It supports structured requisition management, configurable posting and qualification requirements, candidate and application tracking, interviews, evaluator scoring, and formal selection decisions. The module is designed to work across public sector, commercial, and regulated environments, enabling use cases such as merit-based civil service hiring, corporate recruiting, campus hiring, internal mobility, and high-volume talent acquisition. It integrates with configurable question-and-answer capabilities for screening and leverages shared skills/competencies for defensible evaluation. The module concludes with offer management and pre-hire requirements, providing a clean handoff to HR Administration for onboarding and employment processing."
    
    "hr-benefits" = "The **HR Benefits module** manages the full lifecycle of employee benefit offerings, from plan design and eligibility configuration to enrollment, life event changes, and cost administration. It allows organizations to define benefit plans, options, coverage levels, providers, and contribution structures, while enforcing eligibility rules and waiting periods. HR staff can manage open enrollment cycles, process new hire enrollments, handle qualifying life events (such as marriage or birth), maintain beneficiary records, and track benefit-related claims or reimbursements. The module also supports payroll integration through deduction codes and contribution rates, and enables financial oversight through cost allocation tracking. It is designed to support both public sector and commercial organizations with effective dating, auditability, and structured benefit governance."
    
    "gamification" = "The **Gamification** module provides a structured way to encourage, track, and recognize desired behaviors across programs, teams, and initiatives. It allows organizations to define Games (time-bound or ongoing initiatives), configure Activities that represent measurable actions, and establish Achievements that participants can earn based on participation or performance. Participants (individuals or teams) generate Activity records through their actions, and when criteria are met, Achievement records are granted and tracked. This module can be used to reinforce training completion, safety compliance, case resolution timeliness, volunteer engagement, productivity milestones, wellness initiatives, community participation, or internal innovation efforts—making it a flexible behavioral reinforcement layer that can operate alongside workforce, compliance, training, service delivery, or operational modules across public or commercial environments."
    
    "hr-administration" = "The **HR Administration module** manages the core employment structure, transactions, and workforce recordkeeping for an organization. It supports position and classification management (positions, job classifications, grades, and ranks), effective-dated employment actions (promotions, reassignments, pay changes, milestones), employee requests (time off, telework, overtime, workplace accommodations, declarations), and related compliance tracking through governing authorities and structured approvals. Typical use cases include maintaining authorized staffing structures, processing personnel actions, tracking leave and overtime activity, managing accommodation workflows, administering grade/rank frameworks in government or structured environments, and maintaining accurate historical employment records. The module serves as the operational system of record for the employee lifecycle while remaining distinct from recruiting, benefits, and performance management."
}

$modules = @(
    @{Path="external-engagement/programs-and-services"; Name="Programs and Services"; Emoji="🎁"; Key="programs-and-services"},
    @{Path="compliance-security/personnel-security"; Name="Personnel Security"; Emoji="🔐"; Key="personnel-security"},
    @{Path="shared/shift-scheduling"; Name="Shift Scheduling"; Emoji="🔧"; Key="shift-scheduling"},
    @{Path="administrative/executive-coordination"; Name="Executive Coordination"; Emoji="🎯"; Key="executive-coordination"},
    @{Path="operations/project-tracking"; Name="Project Tracking"; Emoji="📋"; Key="project-tracking"},
    @{Path="administrative/member-organizations"; Name="Member Organizations"; Emoji="👥"; Key="member-organizations"},
    @{Path="external-engagement/external-interaction"; Name="External Interaction"; Emoji="💬"; Key="external-interaction"},
    @{Path="financial/financial-management"; Name="Financial Management"; Emoji="💰"; Key="financial-management"},
    @{Path="workforce/training-and-certification"; Name="Training and Certification"; Emoji="🎓"; Key="training-and-certification"},
    @{Path="workforce/time-travel-expenses"; Name="Time, Travel, and Expenses"; Emoji="⏱️"; Key="time-travel-expenses"},
    @{Path="operations/operational-excellence"; Name="Operational Excellence"; Emoji="🎯"; Key="operational-excellence"},
    @{Path="compliance-security/investigations"; Name="Investigations"; Emoji="🔍"; Key="investigations"},
    @{Path="operations/it-service-management"; Name="IT Service Management"; Emoji="💻"; Key="it-service-management"},
    @{Path="workforce/hr-recruiting"; Name="HR Recruiting"; Emoji="🎯"; Key="hr-recruiting"},
    @{Path="workforce/hr-benefits"; Name="HR Benefits"; Emoji="💼"; Key="hr-benefits"},
    @{Path="workforce/gamification"; Name="Gamification"; Emoji="🎮"; Key="gamification"},
    @{Path="workforce/hr-administration"; Name="HR Administration"; Emoji="👥"; Key="hr-administration"}
)

foreach ($module in $modules) {
    $modulePath = Join-Path $rootPath $module.Path
    $buildFile = Join-Path $modulePath "BUILD.md"
    
    Write-Host "Updating $($module.Name)..." -ForegroundColor Cyan
    
    $description = $descriptions[$module.Key]
    if ($description) {
        $newContent = "# $($module.Emoji) $($module.Name)`n`n$description`n`n# Completed`n`n# Planned`n"
        Set-Content -Path $buildFile -Value $newContent -NoNewline
        Write-Host "  Updated successfully" -ForegroundColor Green
    } else {
        Write-Host "  No description available" -ForegroundColor Yellow
    }
}

Write-Host "`nAll modules with descriptions updated!" -ForegroundColor Green
